### ISSUE TITLE
議程表呈現調整建議

### ISSUE THREAD

**Issue by chihaoyo** [g0v/summit2018#105]
1. 議程表中四天（四個 column）固定等寬
2. 每格 session 的講者姓名之間，加入分隔符號，更清楚分隔講者
  a. 英文建議用半形逗號加半形空格（`, `）
  b. 中文建議用頓號（`、`）
3. 視覺上區隔不同種類的 session
  a. 目前 airtable 中會標註是 talk OR panel OR workshop OR keynote
  b. 用文字加註或格子的背景顏色好像都可以

以上建議，不知道可不可行？再請網站組的夥伴提出意見，多謝！

### TODO:
- [x] `1.`、`2.`、`3.`、分軌標題、同一軌中的分隔線、
- [ ] 分軌標題的 tooltip 顯示150介紹
- [ ] Q&A 的文字樣式、上方分隔線

**Comment by choznerol** [comment]
ok~~ 1 跟 2 我先改，3 我可能再跟設計師討論一下~ 想知道這部分大概什麼時候會算是公開？如果是這幾天我就先加字

**Comment by choznerol** [comment]
需要設計的部分已轉告設計師，細節也可以在 invision 裡討論，1 跟 2 改完了但還沒空上@@ 應該明天會上
https://invis.io/3VMJFRNTYXG#/308786949_g0v_-2-

**Comment by choznerol** [comment]
3 設計師完成了~ 應該這兩天會上；雙語的話猜應該也是這幾天~

**Comment by ipaaa** [comment]
![40858872_1752476061544804_462235865138069504_n](https://user-images.githubusercontent.com/2939042/45068415-e8919380-b0f9-11e8-8b0b-f2487078ab87.jpg)
現在分隔很清楚好看，但有沒可能把分軌標題獨立成一欄並加上說明文字（如圖式）。
因為目前是以分軌標題、三個 talk 一組。（目前看起來分軌標題是跟著第一個 talk）

**Comment by chihaoyo** [comment]
@choznerol 分軌標題、說明都麻煩預留中英欄位，QA 是什麼意思我沒有很懂 XD

**Comment by chihaoyo** [comment]
中英分軌標題補完。

**Comment by choznerol** [comment]
@ipaaa Q&A 要麻煩你解釋下~ 我是看上面的圖跟rainie的設計裡有

**Comment by choznerol** [comment]
@chiahao 補上說明的英文欄位，再麻煩囉（不確定我們誰會先出XD 但應該也會比照講者及議程那樣中英互補）

**Comment by ipaaa** [comment]
@choznerol QA只是畫圖時的示意 XD 
請用原本 chihao 的用語

**Comment by choznerol** [comment]
根據群組討論先 close，再麻煩 @ipaaa 開 issue 另個囉
