### ISSUE TITLE
在首頁及議程頁都增加「有雙向口譯」資訊

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2018#136]
位置：首頁大標題處、議程頁最上方明顯處
中文：大會議程皆有華英語雙向即時口譯
英文: All sessions will have simultaneous  interpretion between English and Mandarine

**Comment by ipaaa** [comment]
1) 需要大一點、更明顯  QQ （因為一直有人很焦慮來問）
2) 英文少了 "All"

<img width="756" alt="screen shot 2018-09-14 at 13 12 31" src="https://user-images.githubusercontent.com/2939042/45530949-05c41180-b820-11e8-989f-bb3048224acc.png">

<img width="764" alt="screen shot 2018-09-14 at 13 12 25" src="https://user-images.githubusercontent.com/2939042/45530956-0b215c00-b820-11e8-98bd-9f2977dc7f61.png">

**Comment by yoyo930021** [comment]
已改完
