### ISSUE TITLE
首頁拿掉地圖連結？

### ISSUE THREAD

**Issue by choznerol** [g0v/summit2018#145]
目前的地圖連結在 hero image 上很容易卡到，現在 [交通頁面](https://summit.g0v.tw/2018/transport) 上也有地圖了，後續可能會考慮拿掉喔

cc @ipaaa @chiahao Rainie

![screen shot 2018-09-13 at 11 47 56 pm](https://user-images.githubusercontent.com/12410942/45499695-8139aa80-b7af-11e8-82ef-1f900fdc2b65.png)
![screen shot 2018-09-13 at 11 47 50 pm](https://user-images.githubusercontent.com/12410942/45499696-8139aa80-b7af-11e8-88a2-ff0fc498770e.png)
![screen shot 2018-09-13 at 11 47 40 pm](https://user-images.githubusercontent.com/12410942/45499697-8139aa80-b7af-11e8-87d1-0809d4659ac9.png)

**Comment by ipaaa** [comment]
好！拿掉+1 
 @choznerol
