### ISSUE TITLE
加「主辦單位」「合作單位」「議程協力」「共力夥伴」等等欄位

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2018#150]
1) airtable 需要輸入的欄位
2) 顯示順序：
主辦單位 (g0v summit 2018)
合作單位 (ocf, iis, jothon)
共力夥伴 (科會辦 tca）
支持單位
議程協力
合作夥伴（hackmd 等）

同 2016
https://summit.g0v.tw/2016/
<img width="766" alt="screen shot 2018-09-14 at 16 50 11" src="https://user-images.githubusercontent.com/2939042/45540165-49c60f00-b83e-11e8-9268-e48c714c2066.png">

**Comment by yoyo930021** [comment]
除了 合作夥伴 以外
其他都已上線

**Comment by choznerol** [comment]
@ipaaa 移到 #152 囉
