### ISSUE TITLE
「贊助大會、媒體聯繫、媒體註冊」也加在「一般票、個人贊助票」下面

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2018#164]
有人來詢問媒體聯繫，說網站上找不到 ><

原位置保留，另新增按鈕放「一般票、個人贊助」下面

<img width="641" alt="screen shot 2018-09-17 at 14 34 58" src="https://user-images.githubusercontent.com/2939042/45608690-e7ac1a80-ba86-11e8-8beb-afc12e208982.png">

**Comment by choznerol** [comment]
...蛤我覺得這樣還找不到蠻瞎的耶@@ 而且加到五顆按鈕一定會大破版

**Comment by choznerol** [comment]
如果選一顆最重要的加呢

**Comment by ipaaa** [comment]
好吧，加五顆的確太爆 XDD 
加「媒體聯絡」

**Comment by choznerol** [comment]
ok！
