### ISSUE TITLE
合作夥伴 Partners 頁，最後一列加「個人贊助」

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2018#168]
因為有開個人贊助頁，其中有問是否要網站露出
目前有兩位可以露出大頭
https://g0v-summit2018.kktix.cc/events/conf-donate

請增加一列
個人贊助，airtable 可加大頭

**Comment by choznerol** [comment]
airtable已先開欄位了，前端待補

**Comment by ipaaa** [comment]
@choznerol 先用一個簡單的方式上上看？XD 
下午我跟 bess 來丟幾個資料

**Comment by choznerol** [comment]
ok~

**Comment by choznerol** [comment]
那我要先確認一點~ 個人贊助應該只會有頭、文字（、連節），不會有文字描述對嗎

**Comment by choznerol** [comment]
除了名字跟照片，會有title或個人連結嗎

**Comment by ipaaa** [comment]
好，類似講者頁作法+1

**Comment by choznerol** [comment]
ok!

**Comment by choznerol** [comment]
closed by #187
