### ISSUE TITLE
贊助商 Logo 透明度降低

### ISSUE THREAD

**Issue by shadowcrow0** [g0v/summit2018#180]
現在的網站下方贊助商 Logo 點開之後，贊助商文字簡介跟贊助商 logo 疊起來會看不清楚，建議提高贊助商的 logo 透明度

**Comment by choznerol** [comment]
logo 在點開之前是很清楚的
![screen shot 2018-09-23 at 10 37 39 am](https://user-images.githubusercontent.com/12410942/45923590-04c86980-bf1d-11e8-9c0a-f0a1585f236b.png)

覺得點開之後應該會以字看得清楚為優先耶，畢竟這兩者是衝突的。稍微試了一下：
目前（opacity: 0.8）
![screen shot 2018-09-23 at 10 37 34 am](https://user-images.githubusercontent.com/12410942/45923588-f9753e00-bf1c-11e8-87ba-ee29b936e9db.png)

調高透明度（opacity: 0.5），logo 也沒有很清楚，但字已經完全看不到了 @@
![screen shot 2018-09-23 at 10 38 13 am](https://user-images.githubusercontent.com/12410942/45923587-f9753e00-bf1c-11e8-85f1-6874372f84f9.png)

**Comment by ipaaa** [comment]
我想「提高透明度」的意思，應該是 Logo 透明「數值降低」到 0.2-0.3 喔？ XD
昨天我們一起發現XD 
@choznerl @shadowcrow0

**Comment by choznerol** [comment]
喔喔喔瞭解XD 原來是這個意思

**Comment by shadowcrow0** [comment]
對不起，我想講降低，然後打成調高了
