### ISSUE TITLE
staff 英文版

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2018#182]
工作人員 title 英文版不見了？
可補回來否？

**Comment by choznerol** [comment]
@yoyo930021 一開始有嗎@@

**Comment by ipaaa** [comment]
有欸，是 chihao 逐一翻譯的

**Comment by ipaaa** [comment]
https://docs.google.com/document/d/1Oj6eFkjkmEyoUTWWkun3kwWJJ0BZzKmeg1t-tCjhjfU/edit  有空可以用這個補上英文分組 title 嗎？我不確定是放哪一欄？

@choznerol

**Comment by choznerol** [comment]
那不用放airtable，我直接改在code
