### ISSUE TITLE
加「開放工作坊」、「大會共筆」、「口譯連結」、「直播資訊」、「社群動態」等連結

### ISSUE THREAD

**Issue by ipaaa** [g0v/summit2018#188]
<img width="652" alt="screen shot 2018-09-28 at 18 33 50" src="https://user-images.githubusercontent.com/2939042/46203674-178fd380-c34d-11e8-995f-84180b2bd1c3.png">

加「開放工作坊」、「大會共筆」、「口譯連結」、「直播資訊」、「社群動態」等連結
醜一點沒關係，先加 button 吧

大會共筆：https://g0v.hackmd.io/c/summit18
開放工作坊：https://beta.hackfoldr.org/g0v-Summit-2018-unconf
即時口譯資訊：https://g0v.auxala.com
直播資訊：https://www.youtube.com/user/g0vTW
社群動態：https://www.juicer.io/g0vsummit

**Comment by choznerol** [comment]
@ipaaa 

**直播**會有自己的 tab

**即時口譯**跟**大會共筆**我覺得大家可能比較會預期到「議程」頁找，可以放在目前「大會議程皆有華英語雙向即時口譯」的位置，當然一定會比目前的字再更明顯

**開放工作坊**我會在議程的格子（如下圖）加上超連結： cc @chiahao 
![image](https://user-images.githubusercontent.com/12410942/46240424-deea0b80-c3d9-11e8-9208-033a66a8bccf.png)
![image](https://user-images.githubusercontent.com/12410942/46240456-4dc76480-c3da-11e8-90c7-e67c8e3ab666.png)

**Juicer**我看他寫可以內嵌在網站，但可能需要幫我加個權限，這個要找誰～？

**Comment by choznerol** [comment]
@ipaaa 

- **直播**會有自己的 tab

- **即時口譯**跟**大會共筆**我覺得大家可能比較會預期到「議程」頁找，可以放在目前「大會議程皆有華英語雙向即時口譯」的位置，當然一定會比目前的字再更明顯

- **開放工作坊**我會在議程的格子（如下圖）加上超連結： cc @chihaoyo 
![image](https://user-images.githubusercontent.com/12410942/46240424-deea0b80-c3d9-11e8-9208-033a66a8bccf.png)
![image](https://user-images.githubusercontent.com/12410942/46240456-4dc76480-c3da-11e8-90c7-e67c8e3ab666.png)

- **Juicer**我看他寫可以內嵌在網站，但可能需要幫我加個權限，這個要找誰～？

**Comment by choznerol** [comment]
大概會像這樣
![image](https://user-images.githubusercontent.com/12410942/46240675-7ac94680-c3dd-11e8-82d7-d013e116534c.png)

**Comment by yutin1987** [comment]
由於當天

大會共筆：https://g0v.hackmd.io/c/summit18
開放工作坊：https://beta.hackfoldr.org/g0v-Summit-2018-unconf
即時口譯：https://g0v.auxala.com
即時字幕：待補
<del>直播資訊：https://www.youtube.com/user/g0vTW</del>
社群動態：https://www.juicer.io/g0vsummit

使用頻率會很高，目前的位置不易被發現

<img width="443" alt="2018-09-29 4 36 24" src="https://user-images.githubusercontent.com/2505934/46243413-b593a480-c406-11e8-82e8-774fa5fc96db.png">

**Comment by choznerol** [comment]
那全部放 navbar ~?

**Comment by ipaaa** [comment]
Navbar已經太擠
還是比照2016，暴力排列在右側吧
五個現場最常用的放一起
@yutin1987 今天說有空pr一版

**Comment by choznerol** [comment]
closed by #198
