### ISSUE TITLE
講者列表中主持人重複

### ISSUE THREAD

**Issue by Zekt** [g0v/summit2018#192]
https://summit.g0v.tw/2018/speakers
clkao、Peace、Peggy 等人重複，已經確認 Airtable 中也是重複的，
但兩個主持人點下去的行為不同，一個會跳至議程介紹，一個會跳至該軌，我不確定該刪掉哪個

**Comment by choznerol** [comment]
都不要刪~~ 這算是預期的行為，因為一開始的架構設計沒有考慮到會有分軌、分軌主持人，還會有主持人跟議程講者同一人的狀況，所以除非完全不顯示主持人不然要怎麼改都會有點麻煩。不過剛發現兩個 clkao 都有 `【主持人】clkao` 是有問題的，已經把 airtable 的 `IS_MODERATOR` 勾掉，現在應該會變成這樣：

![image](https://user-images.githubusercontent.com/12410942/46242595-57ae8f00-c3fd-11e8-8528-ce4318752493.png)

![image](https://user-images.githubusercontent.com/12410942/46242645-c8ee4200-c3fd-11e8-921a-3c9979b3c353.png)

點擊`【主持人】clkao` 這個才會是連到議程表打開分軌簡介
