### ISSUE TITLE
調整 flickr 相簿順序

### ISSUE THREAD

**Issue by choznerol** [g0v/summit2018#47]
麻煩 @zbryikt 協助把 [summit-2018-carousel 相簿](https://www.flickr.com/photos/g0v/albums/72157692801078814) 裡的 [這張大合照](https://www.flickr.com/photos/g0v/26460319244/in/album-72157692801078814) 移到相簿第一張，方便首頁的排版，因為嵌入元件的長寬是由第一張照片決定

**Comment by zbryikt** [comment]
調了順序也設了封面，不過似乎還是會顯示原本那一張。

**Comment by choznerol** [comment]
恩恩前端也要改一下
