### ISSUE TITLE
首頁 按鈕

### ISSUE THREAD

**Issue by besscsl** [g0v/summit2018#65]
**我要贊助** 按鈕左邊增加新按鈕 **Call for Paper**
連結待補

**Comment by choznerol** [comment]
昨天有討論到贊助不太是從網頁來所以 Sponsor Us 按鈕不一定要放在首頁
https://g0v-tw.slack.com/archives/G7M8WR1QR/p1523362964000437
然後突然要放的早鳥票、贊助票連結沒地方放，先放到原本 Sponsor Us 的位置了（`/sponsors` 頁面還是有 Sponsor Us 按鈕/信像）
之後的 CFP 不知道是會也放這，還是就只有分頁
cc @clkao 有什麼concern嗎？都可以再改

**Comment by besscsl** [comment]
補連結：https://docs.google.com/document/d/1ErCqlMQapiUlpFp-hjQPPc5Y99O5OmCAnK1wy8NudKY/edit#heading=h.c8t217imjz30
