### ISSUE TITLE
增加 email

### ISSUE THREAD

**Issue by besscsl** [g0v/summit2018#77]
贊助和公關加較明顯處（如上屆），總籌 email 放 footer。

贊助大會
g0v-summit-partner-2018@googlegroups.com
（partner-2018@summit.g0v.tw）
媒體聯繫
g0v-summit-2018-pr@googlegroups.com
年會總籌組
g0v-summit-committee-2018@googlegroups.com

**Comment by choznerol** [comment]
@besscsl   @@ 現在才看到，晚上來加

**Comment by choznerol** [comment]
@besscsl 咦所以 `g0v-summit-partner-2018@googlegroups.com` 跟 `partner-2018@summit.g0v.tw` 是要放哪個？

**Comment by choznerol** [comment]
@besscsl tooltip 的文字要改成 mail to commit 嗎

![screen shot 2018-08-24 at 9 25 57 am](https://user-images.githubusercontent.com/12410942/44559944-c144d900-a77f-11e8-86fb-34dc41725531.png)
