### ISSUE TITLE
首頁地圖連結 Safari 上位置錯誤

### ISSUE THREAD

**Issue by yoyo930021** [g0v/summit2018#86]
<img width="1680" alt="2018-07-28 2 32 03" src="https://user-images.githubusercontent.com/9126398/43353796-0acfa4dc-9273-11e8-8e8c-370233b72d74.png">

**Comment by choznerol** [comment]
感謝回報，這兩天才看到＠＠  應該這幾天會跟[首頁改版](https://invis.io/3VMJFRNTYXG)一起改
